<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Pegawai;
use App\Models\Bagian;
use App\Models\Employee;
use App\Models\Section;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PegawaiSeeder extends Seeder
{
    public function run()
    {
        $bagianIds = Section::pluck('id')->toArray();

        $pegawai = [
            [
                'nip' => '2024010001',
                'nama' => 'Budi Santoso',
                'email' => 'budi.santoso@example.com',
                'telepon' => '081234567890',
                'alamat' => 'Jl. Merdeka No. 123, Jakarta',
                'bagian_id' => $bagianIds[0], // IT
                'no_rekening' => '1234567890',
                'nama_rekening' => 'BUDI SANTOSO',
                'bank' => 'BCA',
                'shift' => 'full_day',
                'gaji_pokok' => 8000000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 50000,
                'uang_makan_tanggal_merah' => 75000,
                'rate_lembur' => 30000,
                'rate_lembur_tanggal_merah' => 45000,
                'jabatan' => 'IT Manager',
                'tgl_masuk' => '2022-01-15',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010002',
                'nama' => 'Siti Rahayu',
                'email' => 'siti.rahayu@example.com',
                'telepon' => '081234567891',
                'alamat' => 'Jl. Sudirman No. 45, Jakarta',
                'bagian_id' => $bagianIds[1], // HR
                'no_rekening' => '1234567891',
                'nama_rekening' => 'SITI RAHAYU',
                'bank' => 'Mandiri',
                'shift' => 'pagi',
                'gaji_pokok' => 7500000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 50000,
                'uang_makan_tanggal_merah' => 75000,
                'rate_lembur' => 25000,
                'rate_lembur_tanggal_merah' => 37500,
                'jabatan' => 'HR Supervisor',
                'tgl_masuk' => '2022-02-20',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010003',
                'nama' => 'Agus Wijaya',
                'email' => 'agus.wijaya@example.com',
                'telepon' => '081234567892',
                'alamat' => 'Jl. Thamrin No. 78, Jakarta',
                'bagian_id' => $bagianIds[2], // Finance
                'no_rekening' => '1234567892',
                'nama_rekening' => 'AGUS WIJAYA',
                'bank' => 'BNI',
                'shift' => 'siang',
                'gaji_pokok' => 9000000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 50000,
                'uang_makan_tanggal_merah' => 75000,
                'rate_lembur' => 35000,
                'rate_lembur_tanggal_merah' => 52500,
                'jabatan' => 'Finance Manager',
                'tgl_masuk' => '2021-11-10',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010004',
                'nama' => 'Rina Dewi',
                'email' => 'rina.dewi@example.com',
                'telepon' => '081234567893',
                'alamat' => 'Jl. Gatot Subroto No. 56, Jakarta',
                'bagian_id' => $bagianIds[3], // Marketing
                'no_rekening' => '1234567893',
                'nama_rekening' => 'RINA DEWI',
                'bank' => 'BRI',
                'shift' => 'full_day',
                'gaji_pokok' => 8500000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 50000,
                'uang_makan_tanggal_merah' => 75000,
                'rate_lembur' => 32000,
                'rate_lembur_tanggal_merah' => 48000,
                'jabatan' => 'Marketing Head',
                'tgl_masuk' => '2023-03-05',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010005',
                'nama' => 'Hadi Prasetyo',
                'email' => 'hadi.prasetyo@example.com',
                'telepon' => '081234567894',
                'alamat' => 'Jl. MH Thamrin No. 12, Jakarta',
                'bagian_id' => $bagianIds[4], // Sales
                'no_rekening' => '1234567894',
                'nama_rekening' => 'HADI PRASETYO',
                'bank' => 'BCA',
                'shift' => 'malam',
                'gaji_pokok' => 7000000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 60000,
                'uang_makan_tanggal_merah' => 90000,
                'rate_lembur' => 28000,
                'rate_lembur_tanggal_merah' => 42000,
                'jabatan' => 'Sales Executive',
                'tgl_masuk' => '2022-07-15',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010006',
                'nama' => 'Maya Indah',
                'email' => 'maya.indah@example.com',
                'telepon' => '081234567895',
                'alamat' => 'Jl. Asia Afrika No. 34, Bandung',
                'bagian_id' => $bagianIds[5], // Operations
                'no_rekening' => '1234567895',
                'nama_rekening' => 'MAYA INDAH',
                'bank' => 'Mandiri',
                'shift' => 'pagi',
                'gaji_pokok' => 6500000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 45000,
                'uang_makan_tanggal_merah' => 67500,
                'rate_lembur' => 22000,
                'rate_lembur_tanggal_merah' => 33000,
                'jabatan' => 'Operations Staff',
                'tgl_masuk' => '2023-01-10',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010007',
                'nama' => 'Dedi Kurniawan',
                'email' => 'dedi.kurniawan@example.com',
                'telepon' => '081234567896',
                'alamat' => 'Jl. Diponegoro No. 89, Surabaya',
                'bagian_id' => $bagianIds[6], // Production
                'no_rekening' => '1234567896',
                'nama_rekening' => 'DEDI KURNIAWAN',
                'bank' => 'BNI',
                'shift' => 'siang',
                'gaji_pokok' => 6000000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 40000,
                'uang_makan_tanggal_merah' => 60000,
                'rate_lembur' => 20000,
                'rate_lembur_tanggal_merah' => 30000,
                'jabatan' => 'Production Supervisor',
                'tgl_masuk' => '2021-08-22',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010008',
                'nama' => 'Linda Sari',
                'email' => 'linda.sari@example.com',
                'telepon' => '081234567897',
                'alamat' => 'Jl. Ahmad Yani No. 67, Semarang',
                'bagian_id' => $bagianIds[7], // Logistics
                'no_rekening' => '1234567897',
                'nama_rekening' => 'LINDA SARI',
                'bank' => 'BRI',
                'shift' => 'full_day',
                'gaji_pokok' => 5500000,
                'periode_gaji' => 'harian',
                'gaji_harian' => 250000,
                'uang_makan' => 35000,
                'uang_makan_tanggal_merah' => 52500,
                'rate_lembur' => 18000,
                'rate_lembur_tanggal_merah' => 27000,
                'jabatan' => 'Logistics Coordinator',
                'tgl_masuk' => '2023-05-18',
                'status' => 'aktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010009',
                'nama' => 'Fajar Nugroho',
                'email' => 'fajar.nugroho@example.com',
                'telepon' => '081234567898',
                'alamat' => 'Jl. Pahlawan No. 23, Yogyakarta',
                'bagian_id' => $bagianIds[8], // Customer Service
                'no_rekening' => '1234567898',
                'nama_rekening' => 'FAJAR NUGROHO',
                'bank' => 'BCA',
                'shift' => 'malam',
                'gaji_pokok' => 5000000,
                'periode_gaji' => 'mingguan',
                'gaji_harian' => 0,
                'uang_makan' => 30000,
                'uang_makan_tanggal_merah' => 45000,
                'rate_lembur' => 15000,
                'rate_lembur_tanggal_merah' => 22500,
                'jabatan' => 'Customer Service',
                'tgl_masuk' => '2022-09-30',
                'status' => 'nonaktif',
                'foto' => null,
            ],
            [
                'nip' => '2024010010',
                'nama' => 'Ratna Wati',
                'email' => 'ratna.wati@example.com',
                'telepon' => '081234567899',
                'alamat' => 'Jl. Hayam Wuruk No. 90, Denpasar',
                'bagian_id' => $bagianIds[9], // R&D
                'no_rekening' => '1234567899',
                'nama_rekening' => 'RATNA WATI',
                'bank' => 'Mandiri',
                'shift' => 'pagi',
                'gaji_pokok' => 9500000,
                'periode_gaji' => 'bulanan',
                'gaji_harian' => 0,
                'uang_makan' => 55000,
                'uang_makan_tanggal_merah' => 82500,
                'rate_lembur' => 40000,
                'rate_lembur_tanggal_merah' => 60000,
                'jabatan' => 'R&D Specialist',
                'tgl_masuk' => '2020-12-01',
                'status' => 'aktif',
                'foto' => null,
            ],
        ];

        foreach ($pegawai as $data) {
            Employee::create($data);
        }

        $this->command->info('10 data pegawai berhasil ditambahkan!');
    }
}
